import dotenv from 'dotenv';
import readline from 'readline';

dotenv.config();

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

console.log('\n🎉 Birthday App - Email Setup Helper\n');
console.log('This will help you configure email for OTP authentication.\n');

const questions = [
  {
    key: 'EMAIL_HOST',
    question: 'Email host (default: smtp.gmail.com): ',
    default: 'smtp.gmail.com'
  },
  {
    key: 'EMAIL_PORT',
    question: 'Email port (default: 587): ',
    default: '587'
  },
  {
    key: 'EMAIL_USER',
    question: 'Your email address: ',
    default: ''
  },
  {
    key: 'EMAIL_PASS',
    question: 'Email password/App Password: ',
    default: '',
    hidden: true
  },
  {
    key: 'EMAIL_FROM',
    question: 'From email (default: same as EMAIL_USER): ',
    default: ''
  }
];

let answers = {};
let currentQuestion = 0;

function askQuestion() {
  if (currentQuestion >= questions.length) {
    // Generate .env file content
    let envContent = '# Email Configuration for OTP\n';
    envContent += '# Generated by setup-email.js\n\n';
    
    envContent += `EMAIL_HOST=${answers.EMAIL_HOST || questions[0].default}\n`;
    envContent += `EMAIL_PORT=${answers.EMAIL_PORT || questions[1].default}\n`;
    envContent += `EMAIL_USER=${answers.EMAIL_USER}\n`;
    envContent += `EMAIL_PASS=${answers.EMAIL_PASS}\n`;
    envContent += `EMAIL_FROM=${answers.EMAIL_FROM || answers.EMAIL_USER}\n\n`;
    envContent += '# Server Configuration\n';
    envContent += 'PORT=3001\n';
    envContent += 'NODE_ENV=development\n';

    console.log('\n✅ Configuration complete!');
    console.log('\n📝 Add this to your .env file:\n');
    console.log('─'.repeat(50));
    console.log(envContent);
    console.log('─'.repeat(50));
    console.log('\n💡 For Gmail users:');
    console.log('   1. Enable 2-Factor Authentication');
    console.log('   2. Generate App Password: https://myaccount.google.com/apppasswords');
    console.log('   3. Use the App Password (not your regular password)\n');
    
    rl.close();
    return;
  }

  const q = questions[currentQuestion];
  const prompt = q.default ? `${q.question}[${q.default}]: ` : q.question;

  rl.question(prompt, (answer) => {
    answers[q.key] = answer.trim() || q.default;
    currentQuestion++;
    askQuestion();
  });
}

askQuestion();
